# Generated by Django 4.1.3 on 2022-11-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='number',
            new_name='phone_number',
        ),
    ]
