# Generated by Django 4.1.3 on 2022-11-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_number_userdetails_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='user_name',
        ),
    ]
