# Generated by Django 4.1.3 on 2022-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_farmersnotebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmersnotebook',
            name='note_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
