# Generated by Django 4.1.3 on 2022-11-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_farmersnotebook_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersnotebook',
            name='note_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
