# Generated by Django 4.1.3 on 2022-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_agriculturalscraps_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('img_name', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Market Category',
                'verbose_name_plural': 'Market Categories',
                'ordering': ['-pk'],
            },
        ),
    ]
