# Generated by Django 4.1.3 on 2022-12-11 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_marketcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcategory',
            name='img_name',
            field=models.ImageField(upload_to='media/category/'),
        ),
        migrations.CreateModel(
            name='MarketForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(blank=True, max_length=80, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=6, null=True)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='media/market')),
                ('prod_description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('RICE_CROP', 'RICE_CROP'), ('CEREAL_CROP', 'CEREAL_CROP'), ('CATTLE', 'CATTLE'), ('MACHINES', 'MACHINES'), ('HERB_CROPS', 'HERB_CROPS'), ('MOUNTAIN_CROPS', 'MOUNTAIN_CROPS'), ('HOME_PRODUCTION', 'HOME_PRODUCTION'), ('SEEDS', 'SEEDS'), ('SEEDLINGS', 'SEEDLINGS'), ('HOME_GARDEN_EQUIPMENT', 'HOME_GARDEN_EQUIPMENT'), ('TUBERS', 'TUBERS'), ('FERTILIZERS', 'FERTILIZERS'), ('FODDER_CROPS', 'FODDER_CROPS'), ('OIL_MILLS', 'OIL_MILLS'), ('OILS', 'OILS'), ('FRUIT_CROPS', 'FRUIT_CROPS'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('GREENS', 'GREENS'), ('EXPORT_CROPS', 'EXPORT_CROPS'), ('CROPS', 'CROPS'), ('TREES', 'TREES'), ('COLD_CROPS', 'COLD_CROPS'), ('HOUSEHOLD_GOODS', 'HOUSEHOLD_GOODS'), ('OTHER_CULTIVATION', 'OTHER_CULTIVATION')], max_length=30, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.userdetails')),
            ],
            options={
                'verbose_name': 'Market Form',
                'verbose_name_plural': 'Market form',
                'ordering': ['-pk'],
            },
        ),
    ]
