# Generated by Django 4.1.3 on 2022-12-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_rename_seller_marketform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketform',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
        ),
    ]
