# Generated by Django 4.1.3 on 2022-12-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_marketcategory_img_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketcategory',
            old_name='img_name',
            new_name='category_img',
        ),
    ]
