# Generated by Django 4.1.3 on 2022-12-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_rename_img_name_marketcategory_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcategory',
            name='title',
            field=models.CharField(blank=True, choices=[('RICE_CROP', 'RICE_CROP'), ('CEREAL_CROP', 'CEREAL_CROP'), ('CATTLE', 'CATTLE'), ('MACHINES', 'MACHINES'), ('HERB_CROPS', 'HERB_CROPS'), ('MOUNTAIN_CROPS', 'MOUNTAIN_CROPS'), ('HOME_PRODUCTION', 'HOME_PRODUCTION'), ('SEEDS', 'SEEDS'), ('SEEDLINGS', 'SEEDLINGS'), ('HOME_GARDEN_EQUIPMENT', 'HOME_GARDEN_EQUIPMENT'), ('TUBERS', 'TUBERS'), ('FERTILIZERS', 'FERTILIZERS'), ('FODDER_CROPS', 'FODDER_CROPS'), ('OIL_MILLS', 'OIL_MILLS'), ('OILS', 'OILS'), ('FRUIT_CROPS', 'FRUIT_CROPS'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('GREENS', 'GREENS'), ('EXPORT_CROPS', 'EXPORT_CROPS'), ('CROPS', 'CROPS'), ('TREES', 'TREES'), ('COLD_CROPS', 'COLD_CROPS'), ('HOUSEHOLD_GOODS', 'HOUSEHOLD_GOODS'), ('OTHER_CULTIVATION', 'OTHER_CULTIVATION')], max_length=30, null=True),
        ),
    ]
