# Generated by Django 4.1.3 on 2022-12-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_alter_marketcategory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketform',
            name='user',
        ),
        migrations.AddField(
            model_name='marketform',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketform',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marketform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marketform',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marketform',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
