# Generated by Django 4.1.3 on 2023-01-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_remove_marketform_user_marketform_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('category', models.CharField(choices=[('FRUIT_CROPS', 'FRUIT_CROPS'), ('TREES', 'TREES'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('FERTILIZERS_MACHINE', 'FERTILIZERS_MACHINE')], default='FLOWERS', max_length=30)),
                ('success_img', models.CharField(blank=True, max_length=3000, null=True)),
                ('exp_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-pk'],
            },
        ),
    ]
