# Generated by Django 4.1.3 on 2023-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
