# Generated by Django 4.1.3 on 2023-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_newtool'),
    ]

    operations = [
        migrations.CreateModel(
            name='WonFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('FRUIT_CROPS', 'FRUIT_CROPS'), ('TREES', 'TREES'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('FERTILIZERS_MACHINE', 'FERTILIZERS_MACHINE')], default='FLOWERS', max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Won Farmer',
                'verbose_name_plural': 'Won Farmers',
                'ordering': ['-pk'],
            },
        ),
    ]
