# Generated by Django 4.1.3 on 2023-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_wonfarmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('FRUIT_CROPS', 'FRUIT_CROPS'), ('TREES', 'TREES'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('FERTILIZERS_MACHINE', 'FERTILIZERS_MACHINE')], default='FLOWERS', max_length=30)),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Economic Market',
                'verbose_name_plural': 'Economic Markets',
                'ordering': ['-pk'],
            },
        ),
    ]
