# Generated by Django 4.1.3 on 2023-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_economicmarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('FRUIT_CROPS', 'FRUIT_CROPS'), ('TREES', 'TREES'), ('VEGETABLES', 'VEGETABLES'), ('FLOWERS', 'FLOWERS'), ('FERTILIZERS_MACHINE', 'FERTILIZERS_MACHINE')], default='FLOWERS', max_length=30)),
            ],
            options={
                'verbose_name': 'Terrace',
                'verbose_name_plural': 'Terraces',
                'ordering': ['-pk'],
            },
        ),
    ]
