# Generated by Django 4.1.3 on 2023-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_terrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('scientist_img', models.CharField(blank=True, max_length=3000, null=True)),
                ('words', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'verbose_name': 'Scientist',
                'verbose_name_plural': 'Scientists',
                'ordering': ['-pk'],
            },
        ),
    ]
