# Generated by Django 4.1.3 on 2023-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_scientist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('steps', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Crop Cultivation',
                'verbose_name_plural': 'Crop Cultivations',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='scientist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terrace',
            name='user',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
