# MARKET CATEGORY

RICE_CROP = "RICE_CROP"
CEREAL_CROP = "CEREAL_CROP"
CATTLE = "CATTLE"
MACHINES = "MACHINES"
HERB_CROPS = "HERB_CROPS"
MOUNTAIN_CROPS = "MOUNTAIN_CROPS"
HOME_PRODUCTION = "HOME_PRODUCTION"
SEEDS = "SEEDS"
SEEDLINGS = "SEEDLINGS"
HOME_GARDEN_EQUIPMENT = "HOME_GARDEN_EQUIPMENT"
TUBERS = "TUBERS"
FERTILIZERS = "FERTILIZERS"
FODDER_CROPS = "FODDER_CROPS"
OIL_MILLS = "OIL_MILLS"
OILS = "OILS"
FRUIT_CROPS = "FRUIT_CROPS"
VEGETABLES = "VEGETABLES"
FLOWERS = "FLOWERS"
GREENS = "GREENS"
EXPORT_CROPS = "EXPORT_CROPS"
CROPS = "CROPS"
TREES = "TREES"
COLD_CROPS = "COLD_CROPS"
HOUSEHOLD_GOODS = "HOUSEHOLD_GOODS"
OTHER_CULTIVATION = "OTHER_CULTIVATION"
FERTILIZERS_MACHINE = "FERTILIZERS_MACHINE"


CATEGORY = [
    (RICE_CROP, RICE_CROP),
    (CEREAL_CROP, CEREAL_CROP),
    (CATTLE, CATTLE),
    (MACHINES, MACHINES),
    (HERB_CROPS, HERB_CROPS),
    (MOUNTAIN_CROPS, MOUNTAIN_CROPS),
    (HOME_PRODUCTION, HOME_PRODUCTION),
    (SEEDS, SEEDS),
    (SEEDLINGS, SEEDLINGS),
    (HOME_GARDEN_EQUIPMENT, HOME_GARDEN_EQUIPMENT),
    (TUBERS, TUBERS),
    (FERTILIZERS, FERTILIZERS),
    (FODDER_CROPS, FODDER_CROPS),
    (OIL_MILLS, OIL_MILLS),
    (OILS, OILS),
    (FRUIT_CROPS, FRUIT_CROPS),
    (VEGETABLES, VEGETABLES),
    (FLOWERS, FLOWERS),
    (GREENS, GREENS),
    (EXPORT_CROPS, EXPORT_CROPS),
    (CROPS, CROPS),
    (TREES, TREES),
    (COLD_CROPS, COLD_CROPS),
    (HOUSEHOLD_GOODS, HOUSEHOLD_GOODS),
    (OTHER_CULTIVATION, OTHER_CULTIVATION),
]

AGRICULTURE_CATEGORY =[
    (FRUIT_CROPS, FRUIT_CROPS),
    (TREES, TREES),
    (VEGETABLES, VEGETABLES),
    (FLOWERS, FLOWERS),
    (FERTILIZERS_MACHINE, FERTILIZERS_MACHINE),
]



# ACTION
BUY = "BUY"
SELL = "SELL"